### ISSUE TITLE
the codes are expired

### ISSUE THREAD

**Issue by jojan5** [Scoofszlo/genshinimpact_codetracker#1]

**Comment by Scoofszlo** [comment]
Hello! Yes, the website hasn't been updated for more than a month as I am busy with academics and stuff. This might be negative for you but I decided to not continue updating the website as it takes me time to update everything. The project still continues but I have decided to make a different version, which is a web app version that works locally on Windows systems with Python installed. I hope this works for you, though you need a laptop or computer for this one to work (it doesn't work on phones unfortunately if I'm correct). There is an installation guide in the README section of this repo. If you have questions, feel free to message here. Thanks!
